<?php
/**
 * Implements hook_preprocess_page().
 */
function layout_body_class_preprocess_page(&$variables) {
  // Get the current layout.
  $layout = layout_get_layout_by_path();
  
  // Check if a layout is active.
  if (!empty($layout->name)) {
    // Add the layout machine name as a class to the body tag.
    $variables['classes'][] = 'layout-' . backdrop_clean_css_identifier($layout->name);
  }
}

